export const REMOVE_CONTRIBUTOR = "MODAL/DOCUMENT_CONTROLS/CONTRIBUTORS/REMOVE";
export const SELECT_CONTRIBUTOR = "MODAL/DOCUMENT_CONTROLS/CONTRIBUTORS/SELECT";
export const LOAD_CONTRIBUTORS = "MODAL/DOCUMENT_CONTROLS/CONTRIBUTORS/LOAD";
export const ADD_CONTRIBUTOR = "MODAL/DOCUMENT_CONTROLS/CONTRIBUTORS/ADD";
export const SET_PERMISSIONS = "MODAL/DOCUMENT_CONTROLS/CONTRIBUTORS/SET_PERMISSIONS";