export const DOCUMENT_CONTROLS = "MODAL/DOCUMENT_CONTROLS/OPEN";
export const CONTRIBUTORS = "MODAL/DOCUMENT_CONTROLS/OPEN/CONTRIBUTORS";
export const VERSIONS = "MODAL/DOCUMENT_CONTROLS/OPEN/VERSIONS";
export const EXPORT = "MODAL/DOCUMENT_CONTROLS/OPEN/EXPORT";
export const IMPORT = "MODAL/DOCUMENT_CONTROLS/OPEN/IMPORT";