export const CREATE_VERSION = "MODAL/DOCUMENT_CONTROLS/VERSIONS/CREATE";
export const DELETE_VERSION = "MODAL/DOCUMENT_CONTROLS/VERSIONS/DELETE";
export const LOAD_VERSIONS = "MODAL/DOCUMENT_CONTROLS/VERSIONS/LOAD";