export const SET_SUBSCRIPTION = "USER/SET_SUBSCRIPTION";
export const CREATE_SHORTCUT = "USER/CREATE_SHORTCUT";
export const DELETE_SHORTCUT = "USER/DELETE_SHORTCUT";
export const SET_CONFIG = "USER/SET_CONFIG";