export const DELETE_DOCUMENT = "DOCUMENT/DELETE_DOCUMENT";
export const LOAD_DOCUMENT = "DOCUMENT/LOAD_DOCUMENT";
export const SAVE_CONTENT = "DOCUMENT/SAVE_CONTENT";
export const LOAD_CONTENT = "DOCUMENT/LOAD_CONTENT";
export const SET_KEY = "DOCUMENT/SET_ENCRYPTION_KEY";