export const TOGGLE_SHOW_FLAG_FILTER = "DOCUMENT/NOTE/TOGGLE_SHOW_FLAG_FILTER";
export const INITIALIZE_RENDER = "DOCUMENT/NOTE/INITIALIZE_RENDER";
export const SET_SEARCH_QUERY = "DOCUMENT/NOTE/SET_SEARCH_QUERY";
export const CHANGE_SCOPE = "DOCUMENT/NOTE/CHANGE_SCOPE";
export const SET_FLAGS = "DOCUMENT/NOTE/SET_FLAGS";