export const SAVE_DOCUMENT = "EXPLORER/TABS/SAVE_DOCUMENT";
export const CREATE_TAB = "EXPLORER/TABS/CREATE_TAB";
export const SELECT_TAB = "EXPLORER/TABS/SELECT_TAB";
export const CLOSE_ALL = "EXPLORER/TABS/CLOSE_ALL";
export const CLOSE_TAB = "EXPLORER/TABS/CLOSE_TAB";
export const HOVER_TAB = "EXPLORER/TABS/HOVER_TAB";