export const CREATE_DOCUMENT = "EXPLORER/USER_INPUT/CREATE_DOCUMENT";
export const CREATE_FOLDER = "EXPLORER/USER_INPUT/CREATE_FOLDER";
export const RENAME_OBJECT = "EXPLORER/USER_INPUT/RENAME_OBJECT";
export const MOVE_OBJECT = "EXPLORER/USER_INPUT/MOVE_OBJECT";